### PR TITLE
Maintenance release

### PR DESCRIPTION
**Pull request by tompesman**
Hi Jeff,

I did some spring cleaning. This PR consists of:

- formatting
- update elixir and erlang
- fixed some deprecations
- fixed the logger
- added a missing method for the Stream module
- switched to the Jason library for JSON parsing

Do you think we can merge this in?

### CODE REVIEW

**Review by jeffutter — APPROVED** [review]

**Comment by jeffutter** [comment]
@tompesman Looks good. Thanks for your contribution. I'm going to add you as a collaborator on this project. I'll see if I can get it set up so you can tag releases and push to hex.pm.

**Comment by tompesman** [comment]
Hi Jeff!

Thank you! I've just created an account on Hex.

What are your thoughts on using semver? For the next release?

Cheers,

**Comment by jeffutter** [comment]
@tompesman I'll need your hex.pm username or email to add you as an owner. Also, I have this repo setup so that travis-ci will publish any version tag (ie 0.3.0) to hex.pm without you needing to be an owner.

As far as semver goes 👍 lets do it. If you want you can try merging this, tagging master as `v1.0.0` and pushing the tag.

**Comment by tompesman** [comment]
@jeffutter my hex.pm username is `tompesman`

**Comment by tompesman** [comment]
@jeffutter  I did the merge, Travis is not really happy about it. Do you know what is happening?

**Comment by jeffutter** [comment]
I think https://github.com/jeffutter/particle-elixir/commit/a545ca921b239c2e2edb291cfc98f7d00c2e7310 fixed the deploy on travis. I think some behavior of Travis-CI changed since the last time this was deployed. However, it looks like it completed now but I'm not seeing it on hex.pm .
I added you as an owner, you can try pushing the package locally if you want.

**Comment by tompesman** [comment]
I did a local push, hex.pm has now version 1.0.0! 🎊

**Comment by jeffutter** [comment]
@tompesman great! Feel free to look into the CircleCI issue if you ever have a chance. It was a hack to login with `hex` and push the package. It may not work anymore.

**Pull request merged**
